image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Install dependencies and AWS CLI
        script:
          - apt-get update
          - apt-get install -y curl unzip sudo
          - curl -sL https://deb.nodesource.com/setup_18.x | bash -
          - apt-get install -y nodejs
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - sudo ./aws/install
          
          - npm install
          - npm run build
          
          - aws configure set default.region ap-south-1
          - export AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain codeartifact-task --output text --query authorizationToken)
          - npm config set registry https://codeartifact-task-454143665149.d.codeartifact.ap-south-1.amazonaws.com/npm/my-app/

          - npm publish
        artifacts:
          paths:
            - build/*
